FROM ubuntu:jammy

ENV TZ="Europe/Berlin"
ENV DEBIAN_FRONTEND=noninteractive

RUN groupadd -g 1000 user \
  && useradd  -u 1000 -m -d /home/user -r -g user user \
  && apt-get update && apt-get install -y apt-utils && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
    wget \
    unzip \
    ca-certificates \
    xz-utils \
    libgtk2.0-0 \
    libdbus-1-3 \
    libdbus-glib-1-2 \
    libxtst6 \
    libatk1.0-0 \
    libcairo2 \
    libfreetype6 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libpango-1.0-0 \
    libx11-6 \
    libx11-xcb1 \
    libxcb-shm0 \
    libxext6 \
    libxfixes3 \
    libxrender1 \
    libxt6 \
    libxcb1 \
    libxcb-shm0 \
    libasound2-dev \
  && rm -rf /var/lib/apt/lists/*

USER user
WORKDIR /home/user

RUN mkdir -pv /home/user/install && cd /home/user/install/ \
  && wget -nv https://matrica.de/download/linux/moneyplex_20_setup64.zip \
  && unzip moneyplex_20_setup64.zip \
  && rm -fv moneyplex_20_setup64.zip
